// Textos de la sección Stock (productos del barbero).

export const copy = {
  titulo: 'Stock',
  periodos: { hoy: 'Hoy', semana: 'Semana', mes: 'Mes' } as const,
  resumen: {
    vendido: 'Vendido en productos',
    comision: 'Tu comisión',
    unidades: 'Unidades',
  },
  miLink: 'Tu link de venta',
  miLinkAyuda: 'Compartilo en tu Instagram. Los pedidos te llegan por WhatsApp.',
  copiado: '¡Copiado!',
  copiar: 'Copiar link',
  tuWhatsapp: 'Tu WhatsApp',
  tuWhatsappPh: '11 5555-1234',
  sinTelefono: 'Cargá tu WhatsApp para que te lleguen los pedidos.',
  productos: 'Tus productos',
  vacio: 'Todavía no cargaste productos.',
  agregar: 'Agregar producto',
  vender: 'Vender',
  sinStock: 'Sin stock',
  quedan: (n: number) => (n === 1 ? 'queda 1' : `quedan ${n}`),
  delLocal: 'del local',
  ventasHoy: 'Ventas del período',
  sinVentas: 'Sin ventas en este período.',
  form: {
    nuevo: 'Nuevo producto',
    editar: 'Editar producto',
    nombre: 'Nombre',
    nombrePh: 'Pomada, shampoo, gorra…',
    precio: 'Precio de venta',
    costo: 'Lo que te costó',
    costoAyuda: 'Para saber cuánto ganás de verdad. Podés dejarlo en cero.',
    stock: 'Unidades',
    comision: 'Tu comisión',
    comisionAyuda: '% que te llevás por cada venta.',
    comisionAyudaFija: 'Lo que te queda por cada unidad vendida.',
    deQuien: '¿De quién es el stock?',
    mio: 'Mío',
    local: 'Del local',
    guardar: 'Guardar',
    borrar: 'Borrar producto',
    confirmarBorrar: '¿Borrar este producto? Las ventas ya hechas se conservan.',
  },
  venta: {
    titulo: 'Vender',
    cantidad: 'Cantidad',
    medioPago: 'Cómo paga',
    efectivo: 'Efectivo',
    transferencia: 'Transferencia',
    cliente: 'Cliente (opcional)',
    clientePh: 'Nombre',
    total: 'Total',
    ganas: 'Ganás',
    confirmar: 'Confirmar venta',
    hecha: '¡Venta registrada! ✓',
  },
};
