// Textos de Ajustes.

export const copy = {
  titulo: 'Ajustes',
  barberia: {
    titulo: 'Tu barbería',
    nombre: 'Nombre',
    barberoActivo: 'Quién usa este teléfono',
    cambiarBarbero: 'Cambiar de barbero',
    cambiarBarberoAyuda: 'Cierra la sesión en este teléfono y pide el PIN de nuevo.',
    confirmarCambiar: '¿Salir de esta cuenta? Vas a tener que entrar con un PIN.',
  },
  barberos: {
    titulo: 'Barberos',
    agregar: 'Agregar barbero',
    sheet: {
      tituloNuevo: 'Nuevo barbero',
      tituloEditar: 'Editar barbero',
      nombre: 'Nombre',
      nombrePlaceholder: 'Tomi',
      emoji: 'Emoji (opcional)',
      emojiPlaceholder: '⚡',
      comision: 'Comisión (%)',
      comisionAyuda: 'Qué % de lo que factura se lleva el barbero. El resto queda para la barbería.',
      telefono: 'WhatsApp (opcional)',
      telefonoPlaceholder: '11 5555-1234',
      telefonoAyuda: 'Ahí le llegan los pedidos de productos de su link de venta.',
      pin: 'PIN de acceso',
      pinAyuda: 'Con estos 4 números entra desde su teléfono. Pasáselo a él.',
      pinInvalido: 'El PIN tiene que ser de 4 números.',
      pinNuevo: 'Generar otro',
      esDuenio: 'Es dueño',
      esDuenioAyuda: 'Puede ver la facturación completa del local (pestaña Barbería).',
      guardar: 'Guardar',
      quitar: 'Quitar barbero',
      quitarAyuda: 'Se oculta del equipo, pero sus cortes quedan en el historial.',
    },
  },
  servicios: {
    titulo: 'Servicios y precios',
    agregar: 'Agregar servicio',
    minutos: 'min',
    sheet: {
      tituloNuevo: 'Nuevo servicio',
      tituloEditar: 'Editar servicio',
      nombre: 'Nombre',
      nombrePlaceholder: 'Corte + barba',
      precio: 'Precio',
      duracion: 'Duración (min)',
      emoji: 'Emoji (opcional)',
      emojiPlaceholder: '✂️',
      guardar: 'Guardar',
      quitar: 'Quitar servicio',
      quitarAyuda: 'Se deja de ofrecer, pero los cortes viejos no cambian.',
    },
  },
  horario: {
    titulo: 'Horario de atención',
    cerrado: 'Cerrado',
    a: 'a',
  },
  reservas: {
    titulo: 'Link de reservas',
    bajada:
      'Compartilo en tu Instagram o pasáselo a tus clientes: eligen servicio, día y hora, y el turno cae en tu agenda.',
    copiar: 'Copiar link',
    copiado: '¡Copiado!',
    abrir: 'Ver cómo lo ve el cliente',
    aviso:
      'Ojo: por ahora la app vive en este dispositivo. Las reservas hechas desde el teléfono del cliente van a llegar a tu agenda cuando conectemos el backend (Fase 2).',
  },
  google: {
    titulo: 'Google Calendar',
    bajada:
      'Conectá tu Google Calendar y cada turno se agenda ahí solo. Google le manda la invitación y los recordatorios al cliente y a vos.',
    conectado: 'Conectado ✓',
    desconectado: 'Sin conectar',
    conectar: 'Conectar con Google',
    reconectar: 'Reconectar',
    desconectar: 'Desconectar',
    avanzado: 'Usar mi propia cuenta de Google (avanzado)',
    faltaConfig:
      'La conexión directa todavía no está habilitada. Mientras tanto, cada turno tiene el botón "Agregar a Google Calendar".',
    clientId: 'Google OAuth Client ID',
    clientIdPlaceholder: '123...apps.googleusercontent.com',
    faltaClientId: 'Primero pegá tu Client ID de Google (ver abajo).',
    conectando: 'Conectando…',
    error: 'No se pudo conectar. Revisá el Client ID y el dominio autorizado.',
    ayudaTitulo: 'Cómo obtener el Client ID (gratis, una vez)',
    pasos: [
      'Entrá a console.cloud.google.com → creá un proyecto.',
      'APIs y servicios → Biblioteca → activá "Google Calendar API".',
      'Pantalla de consentimiento OAuth → tipo Externo → cargá tu mail.',
      'Credenciales → Crear credenciales → ID de cliente de OAuth → Aplicación web.',
      'En "Orígenes de JavaScript autorizados" pegá el dominio de esta app.',
      'Copiá el Client ID que te da y pegalo acá arriba.',
    ] as string[],
    dominioActual: 'El dominio de esta app es:',
  },
  nube: {
    titulo: 'Respaldo en la nube',
    sinCloud: 'El respaldo en la nube todavía no está habilitado para tu cuenta.',
    tuPlan: 'Tu plan',
    planSinRespaldo:
      'Tu plan no incluye respaldo en la nube ni datos en vivo. Escribinos para pasarte a Pro o Full.',
    codigo: 'Tu membresía',
    ultimoRespaldo: 'Último respaldo',
    nunca: 'todavía no',
    respaldar: 'Respaldar ahora',
    respaldando: 'Respaldando…',
    respaldado: '¡Respaldado! ✓',
    restaurar: 'Restaurar de la nube',
    restaurando: 'Restaurando…',
    confirmarRestaurar:
      'Esto reemplaza los datos de ESTE dispositivo con el último respaldo de la nube. ¿Seguir?',
    error: 'No se pudo. Revisá la conexión.',
    ayuda: 'Tus datos se guardan solos cuando usás la app. Con tu código los recuperás en otro teléfono.',
  },
  datos: {
    titulo: 'Datos',
    demo: 'Cargar datos de demo',
    demoAyuda: '~3 semanas de cortes y turnos de ejemplo para ver la app llena.',
    demoListo: 'Demo cargada. Mirá Stats o la pestaña Barbería.',
    borrar: 'Empezar de cero',
    borrarAyuda: 'Borra todo: cortes, turnos, barberos, servicios y ajustes.',
    confirmarBorrar: '¿Seguro? Se borra TODO y no se puede deshacer.',
  },
};
