// Textos de la Agenda.

export const copy = {
  titulo: 'Agenda',
  nuevoTurno: 'Turno',
  bloquear: 'Bloquear',
  vacio: {
    titulo: 'Nada agendado este día',
    bajada: 'Agendá un turno o compartí tu link de reservas.',
  },
  cerrado: 'La barbería está cerrada este día. Podés cambiar el horario en Ajustes.',
  estados: {
    pendiente: 'Pendiente',
    confirmado: 'Confirmado',
    hecho: 'Hecho',
    cancelado: 'Cancelado',
  } as Record<string, string>,
  origenCliente: 'Reservó por el link',
  turnoSheet: {
    tituloNuevo: 'Nuevo turno',
    tituloEditar: 'Editar turno',
    cliente: 'Nombre del cliente',
    clientePlaceholder: 'Juan Pérez',
    telefono: 'WhatsApp (para confirmarle)',
    telefonoPlaceholder: '11 5555 1234',
    email: 'Email (opcional)',
    emailPlaceholder: 'juan@mail.com',
    servicio: 'Servicio',
    hora: 'Hora',
    sinHorarios: 'No quedan horarios libres para este servicio ese día.',
    nota: 'Nota (opcional)',
    notaPlaceholder: 'Viene con el nene',
    guardar: 'Agendar turno',
    guardarCambios: 'Guardar cambios',
    horaOcupada: 'Ese horario se acaba de ocupar. Elegí otro.',
  },
  bloqueoSheet: {
    titulo: 'Bloquear horario',
    bajada: 'Para cursos, trámites o lo que sea: ese rango no se puede reservar.',
    desde: 'Desde',
    hasta: 'Hasta',
    motivo: 'Motivo (opcional)',
    motivoPlaceholder: 'Curso de fades',
    guardar: 'Bloquear',
    borrar: 'Quitar bloqueo',
    rangoInvalido: 'La hora de fin tiene que ser después de la de inicio.',
  },
  detalle: {
    titulo: 'Turno',
    whatsapp: 'Confirmar por WhatsApp',
    recordatorio: 'Mandar recordatorio',
    agregarGoogle: 'Agregar a Google Calendar',
    email: 'Mandar email',
    confirmar: 'Marcar confirmado',
    hecho: 'Hecho, fichar corte',
    hechoPregunta: '¿Cómo pagó?',
    efectivo: 'Efectivo',
    transferencia: 'Transferencia',
    editar: 'Editar turno',
    cancelar: 'Cancelar turno',
    borrar: 'Borrar turno',
    confirmarBorrar: '¿Borrar este turno? No se puede deshacer.',
    yaFichado: 'Este turno ya está fichado como corte.',
  },
};
